# Use the official Python image as base
FROM python:3.9

# Set the working directory to /app
WORKDIR /app

# Copy the test requirements file into the container at /app
COPY requirements.txt /app

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY . /app

# Run the tests using pytest
CMD ["pytest", "--verbose"]
