version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./database.py:/app/database.py
    depends_on:
      - db
  
  tests:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
    environment:
      DB_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@{POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    command: pytest
